---
resources:
- name: my-git-repo
  type: git
  source:
    uri: https://github.com/ruanbekker/concourse-test
    branch: basic-helloworld

- name: application-repo
  type: git
  source:
    uri: https://github.com/ruanbekker/flask-remote-ip

jobs:
- name: hello-world-job
  public: true
  plan:
  - get: my-git-repo
    trigger: true
  - task: task_print-hello-world
    file: my-git-repo/ci/task-hello-world.yml 

- name: linux-task
  public: true
  plan:
  - get: my-git-repo
  - get: application-repo
    trigger: true
  - task: task_run-linux-task
    file: my-git-repo/ci/task-run-uname.yml
